baseURL = "https://thisvsthat.show"
languageCode = "en-us"
title = "Hoonigan /// This vs. That"
theme = "hoonigan-thisvsthat"

[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
	  unsafe = true

[outputs]
page = ["HTML"]
home = ["HTML"]
section = ["HTML","RSS"]
taxonomyTerm = ["HTML"]
taxonomy = ["HTML"]